### ISSUE TITLE
Anchor tag in home page

### ISSUE THREAD

**Issue by rui-han** [hrcn/pushkin-sitetemplates-default#2]
@jkhartshorne

What is this `<a id="quizzes"> </a>` for? 

It is located in `src/pages/home/index.js`

**Comment by jkhartshorne** [comment]
Did you find the answer to this question?

Either it's necessary to list the quizzes. Or it's not used.

**Comment by rui-han** [comment]
It seems like it's not used.

**Comment by jkhartshorne** [comment]
So this is where it was?

>             <div className="container clearfix">
              <a id="quizzes"> </a>
              <Row className={s.quizwrap}>
                {experiments.map(e => (
                  <QuizTile
                    id={e.shortName}
                    title={e.fullName}
                    duration={e.duration}
                    post={e.tagline}
                    img={require('../../images/' + e.logo)}
                  ></QuizTile>

I agree that it's probably not used.

**Comment by jkhartshorne** [comment]
Can you close this issue?
