### ISSUE TITLE
Experiment tiles are too large

### ISSUE THREAD

**Issue by jkhartshorne** [hrcn/pushkin-sitetemplates-default#5]
Can you please make them approx. 1/2 the size they are now?

**Comment by rui-han** [comment]
Yes. It's a problem I'm solving right now, to make them fixed size, auto line break and left aligned.

**Comment by jkhartshorne** [comment]
Be careful in making them a fixed size. We want this to still display on phones and tablets! That’s part of the reason to use bootstrap to begin with.

**Comment by rui-han** [comment]
Yeah it should be fixed proportion of size with flex display.
